version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=shop_password
      - POSTGRES_DB=shop_db